/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/user/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/user/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["uploadAvatar"];
        post?: never;
        delete: operations["deleteAvatar"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{leagueId}/steal-price": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setStealPrice"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{leagueId}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSettings"];
        put: operations["updateSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{leagueId}/schedule/matches/{matchId}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["correctResult"];
        post: operations["recordResult"];
        delete: operations["revertResult"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{leagueId}/my-mvp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setMyMvp"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{leagueId}/members/{username}/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["promoteToAdmin"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{leagueId}/draft/pool/tiers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setPoolTiers"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{leagueId}/draft/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{leagueId}/closed-list/{entryId}/tier": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["assignTier"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/push-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["registerPushToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/user/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/user/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["loginUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createLeague"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{leagueId}/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTrades"];
        put?: never;
        post: operations["propose"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{leagueId}/trades/{tradeId}/respond": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["respond"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{leagueId}/steal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["steal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{leagueId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{leagueId}/invite/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{leagueId}/draft/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{leagueId}/draft/prepare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["prepareDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{leagueId}/draft/pool/reset-tiers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resetPoolTiers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{leagueId}/draft/pick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["pick"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{leagueId}/draft/auto-pick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["autoPick"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{leagueId}/closed-list/nominate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["nominate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{leagueId}/bench/swap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["swap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{leagueId}/bench/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["release"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{leagueId}/bench/buy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["buy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invite/{token}/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["redeem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{username}/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAvatar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["searchUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["streamUserEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/user/trades/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["myPendingTrades"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pokemons/available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAvailablePokemons"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{leagueId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLeagueDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{leagueId}/standings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStandings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{leagueId}/season-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSeasonStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{leagueId}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSchedule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{leagueId}/my-coins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyCoinBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{leagueId}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete: operations["cancelDraft"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{leagueId}/draft/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{leagueId}/closed-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getClosedList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{leagueId}/bench": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBench"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{leagueId}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getActivityFeed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyLeagues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{leagueId}/trades/{tradeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["cancel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{leagueId}/members/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{leagueId}/closed-list/nominate/{pokemonName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["denominate"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ChangePasswordRequest: {
            currentPassword?: string;
            newPassword?: string;
        };
        AvatarVersionResponse: {
            /** Format: int64 */
            avatarVersion?: number;
        };
        SetStealPriceRequest: {
            pokemonName?: string;
            /** Format: int32 */
            newPrice?: number;
        };
        UpdateLeagueSettingsRequest: {
            /** Format: int32 */
            coinsPerWin?: number;
            /** Format: int32 */
            coinsPerLoss?: number;
            /** Format: int32 */
            priceTierS?: number;
            /** Format: int32 */
            priceTierA?: number;
            /** Format: int32 */
            priceTierB?: number;
            /** Format: int32 */
            priceTierC?: number;
            /** Format: int32 */
            priceTierD?: number;
            seasonStartDate?: string;
            /** Format: int32 */
            maxTeamSize?: number;
            /** Format: int32 */
            tierPctS?: number;
            /** Format: int32 */
            tierPctA?: number;
            /** Format: int32 */
            tierPctB?: number;
            /** Format: int32 */
            tierPctC?: number;
            /** Format: int32 */
            tierPctD?: number;
            /** Format: int32 */
            turnTimerSeconds?: number;
            /** Format: int32 */
            stealWindowCloseDay?: number;
            stealWindowCloseTime?: string;
            /** Format: int32 */
            swapWindowCloseDay?: number;
            swapWindowCloseTime?: string;
        };
        RecordMatchResultRequest: {
            winnerUsername?: string;
            /** Format: int32 */
            winnerScore?: number;
            /** Format: int32 */
            loserScore?: number;
        };
        SetLeagueMvpRequest: {
            pokemonName?: string;
        };
        SetDraftPoolTiersRequest: {
            entryIds?: string[];
            /** @enum {string} */
            tier?: "S" | "A" | "B" | "C" | "D";
        };
        UpdateDraftConfigRequest: {
            /** Format: int32 */
            budget?: number;
            /** Format: int32 */
            priceS?: number;
            /** Format: int32 */
            priceA?: number;
            /** Format: int32 */
            priceB?: number;
            /** Format: int32 */
            priceC?: number;
            /** Format: int32 */
            priceD?: number;
            snake?: boolean;
            turnOrder?: string[];
        };
        AssignTierRequest: {
            /** @enum {string} */
            tier?: "S" | "A" | "B" | "C" | "D";
        };
        TierAdjustmentResponse: {
            changes?: components["schemas"]["TierChangeDto"][];
        };
        TierChangeDto: {
            /** Format: int32 */
            pokemonId?: number;
            pokemonName?: string;
            /** @enum {string} */
            oldTier?: "S" | "A" | "B" | "C" | "D";
            /** @enum {string} */
            newTier?: "S" | "A" | "B" | "C" | "D";
        };
        RegisterPushTokenRequest: {
            token?: string;
        };
        UserRequest: {
            username?: string;
            password?: string;
        };
        LoginResponse: {
            username?: string;
        };
        CreateLeagueRequest: {
            name?: string;
        };
        ProposeTradeRequest: {
            responder?: string;
            proposerPokemonName?: string;
            responderPokemonName?: string;
            /** Format: int32 */
            coinsOffered?: number;
        };
        RespondToTradeRequest: {
            accept?: boolean;
        };
        StealPokemonRequest: {
            targetPokemonName?: string;
        };
        AddMemberRequest: {
            username?: string;
        };
        GenerateInviteLinkResponse: {
            token?: string;
        };
        StartDraftRequest: {
            turnOrder?: string[];
        };
        DraftPickRequest: {
            pokemonName?: string;
        };
        NominatePokemonRequest: {
            pokemonName?: string;
        };
        SwapWithBenchRequest: {
            pokemonToGive?: string;
            pokemonToTake?: string;
        };
        ReleasePokemonRequest: {
            pokemonName?: string;
        };
        BuyFromBenchRequest: {
            pokemonName?: string;
        };
        RedeemInviteResponse: {
            leagueId?: string;
            alreadyMember?: boolean;
        };
        SseEmitter: {
            /** Format: int64 */
            timeout?: number;
        };
        TradeResponse: {
            id?: string;
            leagueId?: string;
            proposer?: string;
            responder?: string;
            proposerPokemonName?: string;
            /** Format: int32 */
            proposerPokemonId?: number;
            responderPokemonName?: string;
            /** Format: int32 */
            responderPokemonId?: number;
            /** Format: int32 */
            coinsOffered?: number;
            status?: string;
            createdAt?: string;
            resolvedAt?: string;
        };
        CurrentUserResponse: {
            username?: string;
            /** Format: int64 */
            avatarVersion?: number;
        };
        AvailablePokemonResponse: {
            /** Format: int32 */
            id?: number;
            name?: string;
            spriteUrl?: string;
            types?: string[];
        };
        LeagueDetailResponse: {
            id?: string;
            name?: string;
            createdBy?: string;
            members?: components["schemas"]["LeagueMemberResponse"][];
            /** @enum {string} */
            status?: "SETUP" | "ACTIVE";
            /** @enum {string} */
            draftStatus?: "PENDING" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED";
        };
        LeagueMemberResponse: {
            username?: string;
            /** @enum {string} */
            leagueRole?: "ADMIN" | "USER";
            /** Format: int64 */
            avatarVersion?: number;
        };
        PlayerStandingResponse: {
            username?: string;
            /** Format: int32 */
            played?: number;
            /** Format: int32 */
            wins?: number;
            /** Format: int32 */
            losses?: number;
            /** Format: int32 */
            coins?: number;
            /** Format: int32 */
            scoreFor?: number;
            /** Format: int32 */
            scoreAgainst?: number;
            /** Format: int32 */
            scoreDiff?: number;
        };
        StandingsResponse: {
            standings?: components["schemas"]["PlayerStandingResponse"][];
        };
        LeagueSettingsResponse: {
            /** Format: int32 */
            coinsPerWin?: number;
            /** Format: int32 */
            coinsPerLoss?: number;
            /** Format: int32 */
            priceTierS?: number;
            /** Format: int32 */
            priceTierA?: number;
            /** Format: int32 */
            priceTierB?: number;
            /** Format: int32 */
            priceTierC?: number;
            /** Format: int32 */
            priceTierD?: number;
            seasonStartDate?: string;
            /** Format: int32 */
            maxTeamSize?: number;
            /** Format: int32 */
            tierPctS?: number;
            /** Format: int32 */
            tierPctA?: number;
            /** Format: int32 */
            tierPctB?: number;
            /** Format: int32 */
            tierPctC?: number;
            /** Format: int32 */
            tierPctD?: number;
            /** Format: int32 */
            turnTimerSeconds?: number;
            /** Format: int32 */
            stealWindowCloseDay?: number;
            stealWindowCloseTime?: string;
            /** Format: int32 */
            swapWindowCloseDay?: number;
            swapWindowCloseTime?: string;
        };
        PlayerSeasonStats: {
            username?: string;
            /** Format: int32 */
            wins?: number;
            /** Format: int32 */
            losses?: number;
            /** Format: int32 */
            played?: number;
            /** Format: int32 */
            winPct?: number;
            /** Format: int32 */
            currentStreak?: number;
            mvpPokemon?: string;
        };
        SeasonStatsResponse: {
            players?: components["schemas"]["PlayerSeasonStats"][];
        };
        JornadaResponse: {
            /** Format: int32 */
            roundNumber?: number;
            matches?: components["schemas"]["MatchResponse"][];
            startDate?: string;
            stealDeadline?: string;
            swapDeadline?: string;
        };
        MatchResponse: {
            id?: string;
            player1?: string;
            player2?: string;
            winnerUsername?: string;
            /** @enum {string} */
            status?: "PENDING" | "COMPLETED";
            /** Format: int32 */
            winnerScore?: number;
            /** Format: int32 */
            loserScore?: number;
        };
        ScheduleResponse: {
            leagueId?: string;
            jornadas?: components["schemas"]["JornadaResponse"][];
            stealWindowOpen?: boolean;
            swapWindowOpen?: boolean;
        };
        CoinBalanceResponse: {
            /** Format: int32 */
            coins?: number;
        };
        DraftConfig: {
            /** Format: int32 */
            budget?: number;
            /** Format: int32 */
            priceS?: number;
            /** Format: int32 */
            priceA?: number;
            /** Format: int32 */
            priceB?: number;
            /** Format: int32 */
            priceC?: number;
            /** Format: int32 */
            priceD?: number;
            snake?: boolean;
        };
        DraftPickResponse: {
            username?: string;
            pokemonName?: string;
            /** Format: int32 */
            pokemonId?: number;
            /** Format: int32 */
            round?: number;
            /** Format: date-time */
            pickedAt?: string;
            /** Format: int32 */
            customStealPrice?: number;
            /** Format: date-time */
            lockedUntil?: string;
            /** Format: int32 */
            price?: number;
        };
        DraftStatusResponse: {
            id?: string;
            /** @enum {string} */
            status?: "PENDING" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED";
            turnOrder?: string[];
            currentTurn?: string;
            /** Format: int32 */
            currentRound?: number;
            picks?: components["schemas"]["DraftPickResponse"][];
            draftHistory?: components["schemas"]["DraftPickResponse"][];
            /** Format: date-time */
            turnDeadline?: string;
            config?: components["schemas"]["DraftConfig"];
            budgets?: {
                [key: string]: number;
            };
        };
        ClosedListEntryResponse: {
            id?: string;
            /** Format: int32 */
            pokemonId?: number;
            pokemonName?: string;
            /** @enum {string} */
            tier?: "S" | "A" | "B" | "C" | "D";
            stats?: components["schemas"]["Stat"][];
            types?: components["schemas"]["Type"][];
            nominatedBy?: string;
            sprite?: string;
        };
        Stat: {
            stat?: components["schemas"]["StatData"];
            /** Format: int32 */
            base_stat?: number;
        };
        StatData: {
            name?: string;
            url?: string;
        };
        Type: {
            type?: components["schemas"]["TypeData"];
            doubleDamageFrom?: string[];
            doubleDamageTo?: string[];
            halfDamageFrom?: string[];
            halfDamageTo?: string[];
            noDamageFrom?: string[];
            noDamageTo?: string[];
        };
        TypeData: {
            name?: string;
            url?: string;
        };
        BenchEntryResponse: {
            /** Format: int32 */
            pokemonId?: number;
            pokemonName?: string;
            sprite?: string;
            tier?: string;
            /** Format: int32 */
            price?: number;
        };
        ActivityEventResponse: {
            id?: string;
            leagueId?: string;
            /** @enum {string} */
            type?: "STEAL" | "BENCH_SWAP" | "BENCH_PURCHASE" | "POKEMON_RELEASED" | "TRADE_COMPLETED" | "MATCH_RESULT" | "MATCH_RESULT_REVERTED" | "TIER_CHANGE" | "COIN_EARNED" | "COIN_REVOKED" | "DRAFT_COINS";
            actorUsername?: string;
            targetUsername?: string;
            pokemonName?: string;
            pokemonName2?: string;
            /** Format: int32 */
            coinsAmount?: number;
            fromTier?: string;
            toTier?: string;
            /** Format: int32 */
            roundNumber?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        ActivityFeedResponse: {
            events?: components["schemas"]["ActivityEventResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            totalPages?: number;
            hasMore?: boolean;
        };
        LeagueResponse: {
            id?: string;
            name?: string;
            createdBy?: string;
            /** Format: int32 */
            memberCount?: number;
            /** @enum {string} */
            status?: "SETUP" | "ACTIVE";
            /** @enum {string} */
            draftStatus?: "PENDING" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    uploadAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AvatarVersionResponse"];
                };
            };
        };
    };
    deleteAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setStealPrice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetStealPriceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LeagueSettingsResponse"];
                };
            };
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLeagueSettingsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    correctResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
                matchId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordMatchResultRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    recordResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
                matchId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordMatchResultRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revertResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
                matchId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setMyMvp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetLeagueMvpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    promoteToAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setPoolTiers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetDraftPoolTiersRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDraftConfigRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    assignTier: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
                entryId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignTierRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TierAdjustmentResponse"];
                };
            };
        };
    };
    registerPushToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterPushTokenRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    loginUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    createLeague: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLeagueRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    getTrades: {
        parameters: {
            query?: {
                history?: number;
            };
            header?: never;
            path: {
                leagueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TradeResponse"][];
                };
            };
        };
    };
    propose: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposeTradeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    respond: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
                tradeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RespondToTradeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    steal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StealPokemonRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    addMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemberRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    generate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GenerateInviteLinkResponse"];
                };
            };
        };
    };
    startDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StartDraftRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    prepareDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resetPoolTiers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    pick: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftPickRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    autoPick: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    nominate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NominatePokemonRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    swap: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwapWithBenchRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    release: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReleasePokemonRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    buy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuyFromBenchRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    redeem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RedeemInviteResponse"];
                };
            };
        };
    };
    getAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    searchUsers: {
        parameters: {
            query: {
                q: string;
                leagueId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string[];
                };
            };
        };
    };
    streamUserEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SseEmitter"];
                };
            };
        };
    };
    myPendingTrades: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TradeResponse"][];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CurrentUserResponse"];
                };
            };
        };
    };
    getAvailablePokemons: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AvailablePokemonResponse"][];
                };
            };
        };
    };
    getLeagueDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LeagueDetailResponse"];
                };
            };
        };
    };
    getStandings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StandingsResponse"];
                };
            };
        };
    };
    getSeasonStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SeasonStatsResponse"];
                };
            };
        };
    };
    getSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScheduleResponse"];
                };
            };
        };
    };
    getMyCoinBalance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CoinBalanceResponse"];
                };
            };
        };
    };
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DraftStatusResponse"];
                };
            };
        };
    };
    cancelDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    streamEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SseEmitter"];
                };
            };
        };
    };
    getClosedList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClosedListEntryResponse"][];
                };
            };
        };
    };
    getBench: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BenchEntryResponse"][];
                };
            };
        };
    };
    getActivityFeed: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                username?: string;
                types?: ("STEAL" | "BENCH_SWAP" | "BENCH_PURCHASE" | "POKEMON_RELEASED" | "TRADE_COMPLETED" | "MATCH_RESULT" | "MATCH_RESULT_REVERTED" | "TIER_CHANGE" | "COIN_EARNED" | "COIN_REVOKED" | "DRAFT_COINS")[];
            };
            header?: never;
            path: {
                leagueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActivityFeedResponse"];
                };
            };
        };
    };
    getMyLeagues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LeagueResponse"][];
                };
            };
        };
    };
    cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
                tradeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    denominate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
                pokemonName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
